modLoader="javafml"
loaderVersion="${loader_version_range}"

license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="damageengine.png"

credits="mitama"

authors="mitama"

description='''
Display damage info on the UI.
'''

[[mixins]]
config="damage-engine.mixins.json"

[[mixins]]
config="damage-engine.client.mixins.json"
clientOnly=true

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
